name: Node CD

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: ssh to serve and deploy
              uses: appleboy/ssh-action@master
              with:
                  host: 35.198.217.27
                  username: nataset
                  key: ${{ secrets.SSH_KEY_SECRET }}
                  port: 22
                  script: |
                      cd webtech/frontend
                      git pull origin main
                      cd ~/webtech
                      docker-compose down
                      docker-compose build frontend
                      docker-compose up
